### ISSUE TITLE
RFC: Please try out the plugin and provide feedback

### ISSUE THREAD

**Issue by marcphilipp** [marcphilipp/nexus-publish-plugin#1]
## Steps

1. Clone or download this repository
2. Follow instructions to try out sample
3. Check Nexus staging repos
4. Try it out in your own projects
5. Provide feedback

**Comment by GeorgeNash** [comment]
Awesome!

Can you publish this to the `Gradle Central Plugin Repository`?

George

**Comment by marcphilipp** [comment]
I will but won’t get to it before next week. In the meantime, you can use it via jitpack.io (see sample project for setup).

**Comment by larsgrefer** [comment]
Hi,

we just successfully deployed to maven central from Travis-CI with this plugin.

See here for the logs: https://travis-ci.org/joinfaces/joinfaces/jobs/453153203#L2143-L2932

Great work 👍

**Comment by marcphilipp** [comment]
I'm glad to hear it! 😊

**Comment by marcphilipp** [comment]
Version 0.1.0 of the plugin has been released to the [Gradle Plugin Portal](https://plugins.gradle.org/plugin/de.marcphilipp.nexus-publish).
