### ISSUE TITLE
Missing release tag for 0.1.0

### ISSUE THREAD

**Issue by szpak** [marcphilipp/nexus-publish-plugin#10]
The version `0.1.0` seems to be [released](https://plugins.gradle.org/plugin/de.marcphilipp.nexus-publish), but there is no a release tag in GitHub. Without that users are not sure which codebase is used in that version and (what's probably more important) people subscribed to that repository won't get any notification about a new version.

**Comment by marcphilipp** [comment]
Thanks for the reminder. I was waiting for the plugin to be approved first in case I needed to make any changes. I've pushed a release tag now.
