### ISSUE TITLE
publishToNexus dependencies

### ISSUE THREAD

**Issue by Vampire** [marcphilipp/nexus-publish-plugin#15]
I'd say the name of this task is a bit misleading anyway?
If you e. g. have publish tasks for an internal repository and for sonatype, this task will depend on all of them, as you conditionless depend on all `PublishToMavenRepository` tasks.
Maybe it would be more helpful if the task actually only depends on the publish tasks that publish to sonatype?

**Comment by marcphilipp** [comment]
Good catch! That's actually a bug introduced in 4c31054898b6f37f7665aa31c3d7a24700d7bdcf. I'd gladly accept a PR that fixes it. 😉

**Comment by Vampire** [comment]
Is the `afterEvaluate` even necessary?
You commented `// PublishToMavenRepository tasks may not yet have been initialized`, but the JavaDoc of `configureEach` says `Configures each element in this collection using the given action, as each element is required. Actions are run in the order added.` which for me means this configuration is done lazily.

**Comment by Vampire** [comment]
@marcphilipp ?

**Comment by marcphilipp** [comment]
I think you're right. Please give it a try. 🙂

**Comment by Vampire** [comment]
I did and didn't see anything failing, just wanted to double-check with you in case I just didn't test the correct edge case :-)

**Comment by Vampire** [comment]
PR sent

**Comment by Vampire** [comment]
Ok, the `afterEvaluate` **is** necessary unfortunately.
