### ISSUE TITLE
Incompatible changes in gradle-nexus-staging-plugin extension

### ISSUE THREAD

**Issue by szpak** [marcphilipp/nexus-publish-plugin#21]
I like the new extension's properties binding and I plan to change the [plain field](https://github.com/Codearte/gradle-nexus-staging-plugin/blob/df4ee7187839b2ef978486950e75c0832948b0f0/src/main/groovy/io/codearte/gradle/nexus/NexusStagingExtension.groovy) (such as `String username`) in gradle-nexus-staging-plugin to `Property<String> username`. As I briefly checked in build.gradle it is handled automatically by Gradle, however, nexus-publish-plugin depends directly on that fields. It's somehow problematic to make a compatibility getters as the return type is changing.

The most straightforward way is to make that change, release the new version of GNSP, make changes in NPP and release the new version. People would have to deal with exception in a case of reusing credentials and having incompatible versions of the plugins. However, maybe you have some better idea how to handle that?

Btw, I'm not sure when I will be doing those changes, but I wanted to start a discussion in advance to have time for some potential mitigation activities.

**Comment by marcphilipp** [comment]
Changing from a plain field to a property is a breaking change. Only Groovy DSL build script that use the assignment syntax will continue to work. Kotlin DSL build scripts and binary plugins will break. The [official recommendation](https://docs.gradle.org/current/userguide/lazy_configuration.html#sec:lazy_configuration_faqs) is to "add a new Property or Provider and deprecate the old one".

If there's sufficient time between deprecation and deletion of the old plain getter/setter, we can add support for both to this plugin.

**Comment by szpak** [comment]
I was thinking about the new properties, but the current names are good and intuitive :). IMHO, it would be more confusing for people to switch to the new properties and sometime in the future back again to the old names with the proper type. Your plugin is probably the only one that integrates directly with GNSP. The Kotlin usage in Gradle configuration also seems to be quite low (although I haven't see any "adoption reports" about that).
The plugin is still before 1.0.0, so breaking changes should be expected and it would be much easier to maintainer the project. I will try to synchronize the changes with you.

**Comment by marcphilipp** [comment]
Makes sense! 👍

**Comment by vlsi** [comment]
@szpak , @marcphilipp , is there a reason why `nexus-publish-plugin` and `nexus-staging` are distinct plugins?

As far as I can tell, the key point of `nexus-publish-plugin` is it can call Nexus API to create a staging repository. Could it be just added to `nexus-staging`?

It would be really crazy if it would require a third plugin to "lookup an ID of an existing staging repository"

**Comment by szpak** [comment]
> As far as I can tell, the key point of `nexus-publish-plugin` is it can call Nexus API to create a staging repository.

@vlsi That's not completely true. In fact `nexus-staging` is able to do it (creating an implicit staging repository) on its own (I use it in some of my integration tests with the old `maven` plugin). The problem here is however, to tell the official maven-publish plugin to upload to the just created repository not to the generic (implicitly created) one. That's the main work which is done by `nexus-publish-plugin`. It would be great to have that feature incorporated into the Gradle itself. Then it would be "just enough" (*) to set that repository ID in `nexus-staging`. However, that logic is heavily Nexus specific and I don't know if @marcphilipp plans to backport it.

**Update**. I precised "it" in my second sentence.

**Comment by vlsi** [comment]
> nexus-staging is able to do it on its own

That's what I mean. It looks like `nexus-staging` should be "just enough" provided it is updated to create a staging repository.

For now, I'm trying to peek the generated ID (for  https://github.com/marcphilipp/nexus-publish-plugin/issues/23 ), and it turns out the ID is not that public:

```kotlin
// We don't know which project will be the first to initialize the staging repository,
// so we watch all the projects
project.allprojects {
    plugins.withId("de.marcphilipp.nexus-publish") {
        tasks.withType<InitializeNexusStagingRepository> {
            val that = this
            doLast {
                // nexus-publish puts stagingRepositoryId to NexusStagingExtension so we get it from there
                val repoName = that.repositoryName.get()
                val stagingRepositoryId = rootProject.the<NexusStagingExtension>().stagingRepositoryId.get()
                // Save the created ID:
                releaseExt.repositoryIdStore.save(repoName, stagingRepositoryId)
            }
        }
    }
}
```

^^^ does the above look obvious? Is it what you expect consumers to write?
I wish I could just access the generated ID directly rather than watch all the tasks in all the projects in order to capture one.

Then there's an impedance mismatch: `nexus-staging` supports single repository only while `nexus-publish` tries to handle multiple ones. So I wonder if we could just add "create staging repository" task to `nexus-staging`.

**Comment by szpak** [comment]
As I already (vaguely) mentioned, that task [exists](https://github.com/Codearte/gradle-nexus-staging-plugin/blob/master/src/main/groovy/io/codearte/gradle/nexus/CreateRepositoryTask.groovy) in `nexus-staging` (mostly) for the testing purpose (and my dirty internal hacks with CDBoy).
When called, it saves the staging repository ID in the `nexus-staging` extension to be reused by the other tasks.

However, it only creates a staging repository in Nexus. You need to handle artifacts upload on your own. In the other case - if you try to use the `publish` task from `maven-publish` - the artifacts will you not be uploaded to that repository.

**Comment by vlsi** [comment]
> the artifacts will you not be uploaded to that repository.

@szpak , thanks, I see

**Comment by marcphilipp** [comment]
@szpak I was already tempted to add tasks for closing and releasing the created staging repos to this plugin because we're now using it internally at Gradle. So we should really consider "merging" our two plugins in one way or another. Since the functionality is Nexus-specific it will definitely not make its way into core Gradle.

**Comment by marcphilipp** [comment]
I'm closing this issue because it's neither a bug report nor feature request. Feel free to open new, more focussed issues.
