### ISSUE TITLE
Support for prepare..vote...release/rollback scenarios

### ISSUE THREAD

**Issue by vlsi** [marcphilipp/nexus-publish-plugin#23]
Hi,

1) @marcphilipp , thank you for your work on Gradle / nexus-publish-plugin it does clarify things

2) What do you think of release workflows when release artifacts have to be voted?
I mean ASF.
The case there is release artifacts have to be staged to a repository, then a vote takes place, then the staging repository is either dropped or promoted.

I think to model that with a state file on the filesystem (e.g. to store current `stagingRepositoryId` and other needed state).

As far as I see `nexus-publish-plugin` always requests `stagingRepositoryId` from Nexus, and I wonder what is the right approach to handle that from your point of view?
Do you think it is a case for enhancement of `nexus-publish-plugin`?
Do you think it is a case for a different plugin?

**Comment by marcphilipp** [comment]
Sounds like for step one you could use this plugin along with the `closeRepository` task from @szpak's nexus-staging plugin. After the vote has taken place, you could set `stagingRepositoryId` of the `nexusStaging` extension and call `releaseRepository`. Would that work for you?

**Comment by vlsi** [comment]
Indeed it should work. Thanks.

**Comment by marcphilipp** [comment]
You're welcome!
