### ISSUE TITLE
Should we be using publish or publishToNexus task?

### ISSUE THREAD

**Issue by rmadisonhaynie** [marcphilipp/nexus-publish-plugin#27]
I would just like to know if we should be using 'publish' or 'publishToNexus' task? I see in the readme the mention of the creation of the 'publishToNexus' task and in the sample to use the 'publish' task.

**Comment by marcphilipp** [comment]
While `publish` publishes all defined publications to all defined repositories, `publishToNexus` publishes all defined publications to the "nexus" repository. Thus, if you haven't set up another repository in the `publishing` block both tasks do the same.
