### ISSUE TITLE
Version number warning 0.2.0 or 0.20.0?

### ISSUE THREAD

**Issue by ghost** [marcphilipp/nexus-publish-plugin#28]
> > Task :initializeNexusStagingRepository
> For increased publishing reliability please update the io.codearte.nexus-staging plugin to at least version 0.20.0.
> If your version is at least 0.20.0, try to update the de.marcphilipp.nexus-publish plugin to its latest version.
> If this also does not make this warning go away, please report an issue for de.marcphilipp.nexus-publish.

I am using 0.2.0 and it looks as though this is the latest. Is this message needed?
Running under gradle 5.3.1 with groovy dsl

**Comment by ghost** [comment]
Sorry, I just realised the 0.20.0 refers to the nexus-staging-plugin, not this plugin. I updated the version and the message went away. All good.

**Comment by marcphilipp** [comment]
No worries! 🙂
