### ISSUE TITLE
Invalid request is sent for service/local/staging/profiles/{id}/start

### ISSUE THREAD

**Issue by vlsi** [marcphilipp/nexus-publish-plugin#30]
The plugin sends `{"data":{"description":{"data":"publishing"}}}` message, however it does not match to the specification.

Here's API: https://oss.sonatype.org/nexus-staging-plugin/default/docs/path__staging_profiles_-profileIdKey-_start.html

Note that extra `<data>` is present only right after top-level element, however it looks like `WrappingTypeAdapterFactory` wraps all the objects with extra `data` which causes invalid `description`.

Apparently, Nexus ignores that and just uses default `Explicitly created` description.

**Comment by vlsi** [comment]
Note: comment is visible in Nexus UI, so it makes sense to put project name + version.

The first two were created with `nexus-publish-plugin` while the last one was created with `nexus-staging-maven-plugin`:
<img width="719" alt="Снимок экрана 2019-04-28 в 23 10 58" src="https://user-images.githubusercontent.com/213894/56869572-fab69e00-6a0a-11e9-94c2-d4b911dbd957.png">

**Comment by marcphilipp** [comment]
Good catch!

**Comment by vlsi** [comment]
By the way, I figured that out when building https://github.com/vlsi/nexus-stub
It caused parse failures, so I just completely ignore request body for now: https://github.com/vlsi/nexus-stub/blob/57dbb30dd34187c87f1825d07a1f49e23106bcd3/src/main/kotlin/com/github/vlsi/nexusstub/staging/StagingProfilesController.kt#L44-L48

**Comment by marcphilipp** [comment]
I've fixed this in https://github.com/marcphilipp/nexus-publish-plugin/commit/cc61011d31a195b46b48f2bbe14a3d16f54b184a.

@vlsi Could you please give it another try with your nexus-stub project?
