### ISSUE TITLE
The staging repository ID is not provided

### ISSUE THREAD

**Issue by pavolloffay** [marcphilipp/nexus-publish-plugin#32]
Hello,

I am run into issues when using this plugin. I am not sure whether it is my configuration or bug in the plugin.

We are getting this error when releasing from travis. Release 
```
 Task :closeRepository
DEPRECATION WARNING. The staging repository ID is not provided. The fallback mode may impact release reliability and is deprecated. Please consult the project FAQ how it can be fixed.
Requested operation wasn't successful in first try. Retrying maximum 50 times with 3 seconds delay between attempts.
Attempt 51/51 failed. WrongNumberOfRepositories was thrown with message 'Wrong number of received repositories in state 'open'. Expected 1, received 4'. Giving up. Configure longer timeout if necessary.
> Task :closeRepository FAILED
> Task :releaseRepository
DEPRECATION WARNING. The staging repository ID is not provided. The fallback mode may impact release reliability and is deprecated. Please consult the project FAQ how it can be fixed.
Requested operation wasn't successful in first try. Retrying maximum 50 times with 3 seconds delay between attempts.
Attempt 51/51 failed. WrongNumberOfRepositories was thrown with message 'Wrong number of received repositories in state 'closed'. Expected 1, received 0'. Giving up. Configure longer timeout if necessary.
> Task :releaseRepository FAILED
FAILURE: Build completed with 2 failures.
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':closeRepository'.
> Wrong number of received repositories in state 'open'. Expected 1, received 4
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================
2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':releaseRepository'.
> Wrong number of received repositories in state 'closed'. Expected 1, received 0
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================
```

Our gradle release configuration is here
loading publish script https://github.com/jaegertracing/jaeger-client-java/blob/master/build.gradle#L125
nexus staging https://github.com/jaegertracing/jaeger-client-java/blob/master/build.gradle#L80
nexus publishing https://github.com/jaegertracing/jaeger-client-java/blob/master/gradle/publish.gradle#L76

everything is applied to all subprojects

Any help is appreciated.

**Comment by marcphilipp** [comment]
Both the `closeRepository` and `releaseRepository` tasks are not provided by this plugin, but by the [gradle-nexus-staging-plugin](https://github.com/Codearte/gradle-nexus-staging-plugin).

**Comment by pavolloffay** [comment]
The release failed because there were multiple staging repositories created. I thought that this plugin would solve that:

> Gradle Plugin that explicitly creates a Staging Repository before publishing to Nexus. This solves the problem that frequently occurs when uploading to Nexus from Travis, namely split staging repositories.

**Comment by marcphilipp** [comment]
@szpak Could you take a look, please?

**Comment by szpak** [comment]
@pavolloffay, I've took a look at your Travis [build](https://travis-ci.org/jaegertracing/jaeger-client-java/jobs/526098222) and it fails as the new mechanism to pass an explicitly created staging repository id is [not active](https://travis-ci.org/jaegertracing/jaeger-client-java/jobs/526098222#L774):
> DEPRECATION WARNING. The staging repository ID is not provided. The fallback mode may impact release reliability and is deprecated. Please consult the project FAQ how it can be fixed.

As a result, a "heuristic" to try to find a staging repository is used which fails as there are some other repositories (probably from the previous runs).

In fact, you don't seem to use the the task(s) provided by nexus-publish-plugin to explicitly create a  staging repository in Nexus and use it to upload the artifacts. As I understand the nexus-publish-plugin logic correctly you should call [`publishToNexus`](https://solidsoft.wordpress.com/2019/02/22/reliable-releasing-to-maven-central-from-travis-using-gradle-2019-edition/) instead of just `publish` (@marcphilipp please correct me, if I'm wrong).

**Comment by marcphilipp** [comment]
Thanks for looking into it, @szpak! Calling `publish` is not an issue, it does the same as `publishToNexus` unless there are other, explicitly defined repos.

I've created a PR to fix the config here: https://github.com/jaegertracing/jaeger-client-java/pull/621

**Comment by szpak** [comment]
Thanks @marcphilipp for pointing it out. Hmm, writing e2e tests for my plugin with the early version of your plugin I believe I had some issues with using just the `publish` task. I will give it an another try and will update my blog post (which I refer in the README).
