### ISSUE TITLE
nexus-publish-plugin + gradle-nexus-staging-plugin = WrongNumberOfRepositories

### ISSUE THREAD

**Issue by slonopotamus** [marcphilipp/nexus-publish-plugin#33]
I'm trying to set up publishing according to [this article](https://solidsoft.wordpress.com/2019/02/22/reliable-releasing-to-maven-central-from-travis-using-gradle-2019-edition/).

Here's my repo: https://github.com/bozaro/git-lfs-java/tree/6464e5d36cb4f7c8f1579a46b740e66e44a11d9f

Travis calls `gradle publishToNexus closeAndReleaseRepository`: https://github.com/bozaro/git-lfs-java/blob/6464e5d36cb4f7c8f1579a46b740e66e44a11d9f/.travis.yml#L43

`nexus-publish-plugin` is set up for child projects: https://github.com/bozaro/git-lfs-java/blob/6464e5d36cb4f7c8f1579a46b740e66e44a11d9f/build.gradle.kts#L43

`nexus-staging-plugin` is set up for root project: https://github.com/bozaro/git-lfs-java/blob/6464e5d36cb4f7c8f1579a46b740e66e44a11d9f/build.gradle.kts#L154

But still, I'm getting:

```
DEPRECATION WARNING. The staging repository ID is not provided. The fallback mode may impact release reliability and is deprecated. Please consult the project FAQ how it can be fixed.
Requested operation wasn't successful in first try. Retrying maximum 20 times with 2 seconds delay between attempts.
```

Followed by build failure:

```
WrongNumberOfRepositories was thrown with message 'Wrong number of received repositories in state 'open'. Expected 1, received 7'. Giving up. Configure longer timeout if necessary.
```

Full build log: https://travis-ci.org/bozaro/git-lfs-java/jobs/533836201

What I am missing?

**Comment by slonopotamus** [comment]
Okay, I think I know what's the problem. I'm trying to use all this machinery for a SNAPSHOT build.

**Comment by slonopotamus** [comment]
Aaaargh. I cannot enable staging for SNAPSHOTs because sonatype [doesn't support staging for snapshots](https://travis-ci.org/bozaro/git-lfs-java/jobs/533845145#L489). So, seems like the only option is to write conditional logic that will call `closeAndReleaseRepository` depending on whether we're building a SNAPSHOT or not, though it is nontrivial to know what repo (snapshot or release) will be used from Travis script.

**Comment by szpak** [comment]
@slonopotamus Definitely. Staging repositories doesn't make much sense for SNAPSHOTs.

I would just use `onlyIf { isSnapshot() }` in your Gradle script (rather than moving it to Bash in Travis) where `isSnapshot` is a method which (most likely) checks if version ends with `-SNAPSHOT` (I believe I have seen that checks in the Gradle itself, but maybe now there is some better option to write that `if`).

**Comment by szpak** [comment]
[That](https://travis-ci.org/bozaro/git-lfs-java/jobs/533880791#L996-L1008) Travis build after your change looks somehow strange:
```
Attempt 10/61 failed. RepositoryInTransitionException was thrown with message 'Repository 'ru[secure]-1032' (in 'open' state) is in transition. Check again later.'. Waiting 10000 ms before next retry.
Getting repository 'ru[secure]-1032'
Requested operation was executed successfully in attempt 11 (maximum allowed 61)
> Task :closeRepository FAILED
:closeRepository (Thread[Daemon worker,5,main]) completed. Took 2 mins 52.871 secs.
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':closeRepository'.
> Wrong 'ru[secure]-1032' repository state 'open' after transition (expected [closed]). Possible staging rules violation. Check repository status using Nexus UI.
```
Can you check that repository in the Nexus UI. There could be some validation errors presented.

**Comment by slonopotamus** [comment]
I'm not quite sure what stuff in gradle script you're suggesting to guard with `onlyIf`.

I could imagine something like: create new task like `publishProperly`, make it depend on `publish` and for releases make it also depend on `closeAndReleaseRepository`.

I disagree with "Staging repositories doesn't make much sense for SNAPSHOTs". For multimodule projects, I want atomic deploys to repo, no matter if it is snapshot or release. Only staging procedure gives such guarantees.

**Comment by slonopotamus** [comment]
Or you mean that I always call `closeAndReleaseRepository` but in `build.gradle` do this?

```
tasks.closeRepository.configure {
    onlyIf { !project.version.toString().endsWith("-SNAPSHOT") }
}

tasks.releaseRepository.configure {
    onlyIf { !project.version.toString().endsWith("-SNAPSHOT") }
}
```

If yes, maybe this logic should go to nexus-publish/nexus-staging? Because you already have logic that decides what repository (release or snapshot) to deploy artifacts to.

**Comment by szpak** [comment]
nexus-staging in general is upload/publish agnostic. You could run it even for the artifacts published earlier (e.g. just by passing the staging repository ID). The plugin doesn't know what is in that repository.
However, in general it most of the cases where nexus-publish integration is enable the current project version determines if it is a snapshot or not.

**Comment by szpak** [comment]
Btw, in Groovy you could write something like that:
```
[tasks.closreRepository, tasks.releaseRepository]. configure {
    onlyIf { !project.version.toString().endsWith("-SNAPSHOT") }
}
```
to reduce duplication. Probably in Kotlin it is also possible.

**Comment by szpak** [comment]
> For multimodule projects, I want atomic deploys to repo, no matter if it is snapshot or release.

Then you can just resign from using `-SNAPSHOT` and just bump a version number by one on every commit/push or CI build.

**Comment by slonopotamus** [comment]
Anyway. I managed to resolve my problem (by using `onlyIf` like you suggested). If you believe there is nothing to improve on nexus-publish/nexus-staging side for projects that deploy both snapshots and releases, feel free to close this issue.

**Comment by marcphilipp** [comment]
I think this should work and remove the duplicated logic:

```kotlin
tasks {
	closeRepository {
    	onlyIf { nexusPublishing.useStaging.get() }
	}
	releaseRepository{
    	onlyIf { nexusPublishing.useStaging.get() }
	}
}
```

**Comment by slonopotamus** [comment]
```
	closeRepository {
    	onlyIf { nexusPublishing.useStaging.get() }
	}
```

This is pretty good, but won't work in multi-project setups where parent project is not published, so it doesn't have `nexus-publish` plugin and thus doesn't have `nexusPublishing` section.

Anyway, thanks for help!
