### ISSUE TITLE
Task publishToSonatype skipped as it has no actions

### ISSUE THREAD

**Issue by ameliariely** [marcphilipp/nexus-publish-plugin#39]
Hi there!

I am using version 0.3.0 and currently unable to publish my library with the following message:
```
> Task :kronos-java:publishToSonatype
Skipping task ':kronos-java:publishToSonatype' as it has no actions.
:kronos-java:publishToSonatype (Thread[Daemon worker,5,main]) completed. Took 0.0 secs.
```

We have sonatype username and password set up in our repository block. https://github.com/lyft/Kronos-Android/blob/master/gradle/publish.gradle
I'd love any direction you could point me in for debugging this. Thank you!

**Comment by ameliariely** [comment]
Figured it out :)

**Comment by mkopylec** [comment]
Could you please tell how have yu solved the issue?
