### ISSUE TITLE
connectTimeout is hardcoded to 1 minute

### ISSUE THREAD

**Issue by slonopotamus** [marcphilipp/nexus-publish-plugin#43]
https://github.com/marcphilipp/nexus-publish-plugin/blob/master/src/main/kotlin/de/marcphilipp/gradle/nexus/internal/NexusClient.kt#L42

I'd either set it to the same value as read/write timeouts or provide a separate option.

**Comment by marcphilipp** [comment]
@slonopotamus Do you have a concrete use case for making this configurable?

**Comment by slonopotamus** [comment]
I'm not sure. Currently, OSS Sonatype Nexus is suffering from severe performance issues and drops connections due to this timeout. If timeout was configurable, I could increase it to see if it helps or not.

**Comment by jpoehnelt** [comment]
>I'm not sure. Currently, OSS Sonatype Nexus is suffering from severe performance issues and drops connections due to this timeout. If timeout was configurable, I could increase it to see if it helps or not.

having same issue with this plugin and sonatype, not sure if this is the solution or not

```
> Task :initializeSonatypeStagingRepository
Task ':initializeSonatypeStagingRepository' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Creating staging repository for stagingProfileId '224a453b33b7aa'

> Task :initializeSonatypeStagingRepository FAILED
:initializeSonatypeStagingRepository (Thread[Execution worker for ':',5,main]) completed. Took 2 mins 32.293 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':initializeSonatypeStagingRepository'.
> java.net.SocketTimeoutException: timeout
```

**Comment by marcphilipp** [comment]
Thanks for the info. In that case, I'd suggest that we add a new `connectTimeout` property to the `NexusPublishExtension`.

@slonopotamus @jpoehnelt Would one of you be interested in submitting a PR?

**Comment by slonopotamus** [comment]
I'll do that, no problem

**Comment by slonopotamus** [comment]
For the reference, here's Sonatype bugreport about this problem: https://issues.sonatype.org/browse/OSSRH-51875
