### ISSUE TITLE
Add check that extra checksums are disabled. 

### ISSUE THREAD

**Issue by nbilyk** [marcphilipp/nexus-publish-plugin#47]
Later versions of Gradle produce 256 and 512 bit hashes, which Sonatype doesn't support on the maven metadata files.  (See issue https://github.com/gradle/gradle/issues/11308)

The solution is for users to add an undocumented property to their builds, but I recommend that this plugin add the following check:
```
require(ExternalResourceResolver.disableExtraChecksums()) { "gradle property systemProp.org.gradle.internal.publish.checksums.insecure=true or CLI flag -Dorg.gradle.internal.publish.checksums.insecure=true must be set." }
```

**Comment by szpak** [comment]
When did you get that errors?

Uploading to Sonatype Nexus yesterday with Gradle 6.0.1 some test project I wasn't needed to add any extra flag. The old and new signatures were uploaded and I was able to close and promote that staging repository.

![image](https://user-images.githubusercontent.com/148013/73493078-4f2fe500-43b2-11ea-80b4-1389b71b55f1.png)

Maybe Sonatype fixed it on the side?

**Comment by marcphilipp** [comment]
Sonatype fixed the issue wrt. sha256 and sha512 checksums for artifacts. But releasing to Maven central currently fails due to those checksums for `maven-metadata.xml`: https://issues.sonatype.org/browse/MVNCENTRAL-5276

**Comment by szpak** [comment]
Those?
![image](https://user-images.githubusercontent.com/148013/73581271-e9625c80-4488-11ea-8326-34d26b0cacd6.png)

It would mean that "No-sync Releases" which I use to do not pollute Maven Central is already fixed or has different validation policies:

![image](https://user-images.githubusercontent.com/148013/73581379-478f3f80-4489-11ea-9d0d-4c043d84299b.png)

But I you @nbilyk hit this error recently with real Maven Central the problem probably still exists.

**Comment by marcphilipp** [comment]
The validation that's triggered when closing the repo does not show any errors in this case. Only when you release the repo it complains about duplicate artifacts.

**Comment by nbilyk** [comment]
Right, I should have been clear that the problem is just in releasing, not staging or closing.  With the flag there are no issues, but that flag isn't documented on the Gradle side and adding a check to this plugin (or forcing the flag if possible) would be very helpful.

**Comment by marcphilipp** [comment]
AFAIK this only affects Maven Central, though. Releasing to other Nexus-based repositories with those checksums should be fine.

**Comment by marcphilipp** [comment]
This plugin is now deprecated in favor of the new [Gradle Nexus Publish Plugin](https://github.com/gradle-nexus/publish-plugin) which provides additional tasks to close and release staging repositories. Please refer to the [migration guide](https://github.com/gradle-nexus/publish-plugin/wiki/Migration-from-gradle_nexus_staging-plugin---nexus_publish-plugin-duo) for details on how to make the switch. If this issue is still relevant to you, please [open a new issue](https://github.com/gradle-nexus/publish-plugin/issues) in the new repository.
