### ISSUE TITLE
Remove `Repository` suffix

### ISSUE THREAD

**Issue by JavierMeep** [marcphilipp/nexus-publish-plugin#50]
Normal task:
- `publishToSonatype`

Meanwhile a specifict platform task:

- `publishMingwX64PublicationToSonatypeRepository`

I think it should be:

- `publishMingwX64PublicationToSonatype`

![image](https://user-images.githubusercontent.com/62933883/106161342-22f6a200-6187-11eb-8743-ee5f480651a9.png)

**Comment by marcphilipp** [comment]
That task name is generated by Gradle so I'm afraid I cannot shorten it. We could make the `publishToSonatype` longer for consistency but I don't think that's what you want, either.
