### ISSUE TITLE
How stagingProfileId is intended to work?

### ISSUE THREAD

**Issue by mockitoguy** [marcphilipp/nexus-publish-plugin#52]
Nice plugin! Question: how does the `stagingProfileId` suppose to work?

My setup:

```
nexusPublishing {
    repositories {
        sonatype {
           stagingProfileId  = "my-custom-name"
        }
    }
}
```

Running `/.gradlew initializeSonatypeStagingRepository` yields:

```
* What went wrong:
Execution failed for task ':shipkit-demo-api:initializeSonatypeStagingRepository'.
> Failed to create staging repository, server responded with status code 404, body: {"errors":[{"id":"*","msg":"Cannot create Staging Repository, profile with id 'my-custom-name' does not exist."}]}
```

I could probably debug this but I figured an issue will serve a documentation :-) Ping @szpak

**Comment by szpak** [comment]
As a quick workaround just remove that line. The staging profile id will be fetch from Nexus automatically based on your project group name.

For longer answer you could refer to [gradle-nexus-staging-plugin](https://github.com/Codearte/gradle-nexus-staging-plugin) where you should configure:
```
nexusStaging {
    packageGroup = "org.mycompany.myproject" //optional if packageGroup == project.getGroup()
    stagingProfileId = "yourStagingProfileId" //when not defined will be got from server using "packageGroup"
}
```
and find one extra task:
```
 - getStagingProfile - gets and displays a staging profile id for a given package group. This is a diagnostic task to get the value and put it into the configuration closure as stagingProfileId.
```
In general, it is advised to set that value. While NPP and GNSP can ask Nexus about that value it can take even 10 seconds (twice).

However, in the context of a need to use both separate plugins, there is a good news for you. To avoid confusion like yours, together with Marc, we've just released a bran new plugin which integrates the functionalities of those two plugin - https://github.com/gradle-nexus/publish-plugin/ . I hope it will work well for you :-).

**Comment by mockitoguy** [comment]
Really looking forward to trying the new plugin!

**Comment by marcphilipp** [comment]
This plugin is now deprecated in favor of the new [Gradle Nexus Publish Plugin](https://github.com/gradle-nexus/publish-plugin) which provides additional tasks to close and release staging repositories. Please refer to the [migration guide](https://github.com/gradle-nexus/publish-plugin/wiki/Migration-from-gradle_nexus_staging-plugin---nexus_publish-plugin-duo) for details on how to make the switch. If this issue is still relevant to you, please [open a new issue](https://github.com/gradle-nexus/publish-plugin/issues) in the new repository.
