### ISSUE TITLE
More preconfiguration for Maven Central publication

### ISSUE THREAD

**Issue by szpak** [marcphilipp/nexus-publish-plugin#9]
To make the plugin even more useful you could consider adding some of the features that are available in the @bmuschko's [gradle-nexus-plugin](https://github.com/bmuschko/gradle-nexus-plugin/) for the original `maven` plugin in Gradle.

Uploading to Maven Central requires a creation of the extra sources and javadocs jars, signing the packages and proper pom.xml configuration. It's somehow boring to define it in every project again and again.

**Comment by larsgrefer** [comment]
@szpak I'm using this plugin successfully in combination with https://plugins.gradle.org/plugin/io.freefair.maven-jars and https://plugins.gradle.org/plugin/io.freefair.maven-publish-java to reduce some of the boilerplate configuration.

This is our full configuration: https://github.com/joinfaces/joinfaces/blob/721f56b3759ee954b089ceb3c8eb3040596cd11e/build.gradle#L174-L229

**Comment by marcphilipp** [comment]
Thanks for the suggestion! However, I consider that beyond the scope of this plugin.
